"""
SQLAlchemy ORM model for customer records.

Defines the database table structure, column types, defaults, and constraints
used to persist customer information such as contact details, activity status,
loyalty points, and creation timestamps.
"""

from datetime import datetime, UTC
from sqlalchemy import Boolean, Column, DateTime, Integer, String
from database import Base


class CustomerSchema(Base):
    """
    SQLAlchemy model representing the Customer database table.

    Defines the database columns, data types, defaults, and
    constraints used to persist customer records.
    """

    __tablename__ = "customer"

    # Primary key automatically generated by the database.
    # Primary keys are automatically unique.
    id = Column(
        Integer,
        primary_key=True,
        autoincrement=True
    )

    # Customer is active by default.
    active = Column(
        Boolean,
        default=True,
        nullable=False
    )

    # Required first name with a maximum database length of 50 characters.
    first_name = Column(
        String(50),
        nullable=False
    )

    # Last name is optional and may be NULL in the database.
    last_name = Column(
        String(50),
        nullable=True
    )

    # Customer email is required and must be unique.
    email = Column(
        String,
        unique=True,
        nullable=False
    )

    # Phone number is required, must be unique,
    # and accommodates the xxx-xxx-xxxx format.
    phone_number = Column(
        String(12),
        unique=True,
        nullable=False
    )

    # Customer loyalty points.
    loyalty_points = Column(
    Integer,
    default=0,
    nullable=False
    )

    # Used to determine the customer's yearly loyalty reset.
    created_at = Column(
        DateTime,
        default=lambda: datetime.now(UTC),
        nullable=False
    )
