"""
Repository layer for vendor-related database operations, including creation,
retrieval, and persistence logic for vendor records.
"""

from sqlalchemy.orm import Session

from vendor.vendor_model import VendorBase
from vendor.vendor_schema import Vendor, VendorSchema


class VendorRepository:
    """
    Provides database operations for vendor records, including creation and
    retrieval of vendor data from the database.
    """

    def __init__(self, db: Session):
        """Initialize the VendorRepository with a database session.

        Args:
            db (Session): An active SQLAlchemy session used to perform
                database operations such as queries, inserts, and commits.
        """
        self.db = db

    def create_new_vendor(self, vendor_data: VendorBase) -> VendorSchema:
        """Create and persist a new vendor record in the database.

        Constructs a new Vendor ORM instance using the provided vendor data,
        adds it to the database session, commits the transaction, and refreshes
        the instance to populate autogenerated fields such as the primary key.

        Args:
            vendor_data (VendorBase): A Pydantic model containing validated
                vendor attributes including name, contact details, and active status.

        Returns:
            Vendor: The newly created Vendor ORM object with all fields populated
                after being committed to the database.

        Raises:
            SQLAlchemyError: If the database transaction fails during commit.
        """
        db_vendor = Vendor(
            active=vendor_data.active,
            name=vendor_data.name,
            contact_name=vendor_data.contact_name,
            contact_role=vendor_data.contact_role,
            email=vendor_data.email,
            phone=vendor_data.phone,
        )
        self.db.add(db_vendor)
        self.db.commit()
        self.db.refresh(db_vendor)

        return db_vendor

    def get_all_vendors(self) -> list[VendorSchema]:
        """Retrieve all vendor records from the database.

        Executes a SELECT query on the Vendor table and returns all results.

        Returns:
            list[Vendor]: A list of Vendor ORM objects representing every vendor
                stored in the database. Returns an empty list if no vendors exist.
        """
        return self.db.query(Vendor).all()

    def get_vendor_by_id(self, vendor_id: int) -> VendorSchema | None:
        """Retrieve a single vendor record by its unique ID.

        Performs a filtered SELECT query using the vendor's primary key. If the
        vendor exists, the corresponding ORM object is returned; otherwise, None
        is returned.

        Args:
            vendor_id (int): The unique identifier of the vendor to retrieve.

        Returns:
            Vendor | None: The Vendor ORM object if found, otherwise None.

        Raises:
            SQLAlchemyError: If the query fails due to database issues.
        """
        return self.db.query(Vendor).filter(Vendor.id == vendor_id).first()
