"""
SQLAlchemy schema for baked goods.

This module defines the BakedGoodSchema database model, which represents
baked goods stored in the database and establishes a relationship with
the Vendor model.
"""

from sqlalchemy import Boolean, Column, Float, ForeignKey, Integer, String, UniqueConstraint
from sqlalchemy.orm import relationship

from database import Base


class BakedGoodSchema(Base):
    """
    Defines the database structure for a baked good.

    Args:
        id: The unique identifier for the baked good. The value is automatically
        generated by the database and is used as the primary key for the baked
        goods table.
        active: Indicates whether the baked good is currently active.
        name: The name of the baked good.
        description: A description of the baked good.
        purchasing_cost: The cost to purchase or produce the baked good.
        retail_price: The price at which the baked good is sold.
        vendor_id: The ID of the vendor associated with the baked good. The value
        creates a foreign key relationship with the vendor table
        and is required, so it cannot be NULL.
        vendor: The vendor associated with the baked good. The relationship connects
        the baked good to the Vendor model and uses the baked_goods relationship on
        the Vendor model to establish a bidirectional relationship.

    Returns:
        A BakedGoodSchema object representing a baked good database record.
    """

    __tablename__ = "baked_good"

    id = Column(Integer, primary_key=True)
    active = Column(Boolean, default=True)
    name = Column(String, nullable=False)
    description = Column(String, nullable=False)
    purchasing_cost = Column(Float, nullable=False)
    retail_price = Column(Float, nullable=False)

    vendor_id = Column(Integer, ForeignKey("vendor.id"), nullable=False)

    vendor = relationship("Vendor", back_populates="baked_goods")

    __table_args__ = (
        UniqueConstraint(
            "name", "vendor_id", name="uq_baked_good_name_vendor"
        ),
    )
